# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-29 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='Voter_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='adhar_uid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='caste',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='family_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='favourite_political_leader',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='favourite_political_party',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politician',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='politician',
            name='religion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
