# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-30 05:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20171130_0430'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Education',
            new_name='PoliticianEducation',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='education',
        ),
    ]
