from django.utils.translation import ugettext_lazy as _
DEFAULT_NATIONALITY_INDIAN='indian'
#______________Address model constants_________________________________

ADDRESS_TYPE_CHOICE_PLOT = "PLOT"
ADDRESS_TYPE_CHOICE_HOME = "HOME"
ADDRESS_TYPE_CHOICE_WORK = "WORK"
ADDRESS_TYPE_CHOICE_OTHER = "OTHER"

ADDRESS_TYPE_TUPLE_PLOT = (ADDRESS_TYPE_CHOICE_PLOT, _("Plot"))
ADDRESS_TYPE_TUPLE_HOME = (ADDRESS_TYPE_CHOICE_HOME, _("Home"))
ADDRESS_TYPE_TUPLE_WORK = (ADDRESS_TYPE_CHOICE_WORK, _("Work"))
ADDRESS_TYPE_TUPLE_OTHER = (ADDRESS_TYPE_CHOICE_OTHER, _("Other"))


ADDRESS_TYPE_CHOICE = (
    ADDRESS_TYPE_TUPLE_PLOT,
    ADDRESS_TYPE_TUPLE_HOME,
    ADDRESS_TYPE_TUPLE_WORK,
    ADDRESS_TYPE_TUPLE_OTHER
)

#_____________Education_MODELS------------------------

EDUCATION_CATEGORY_SSC='ssc'
EDUCATION_CATEGORY_HSC='hsc'
EDUCATION_CATEGORY_DIPLOMA='diploma'
EDUCATION_CATEGORY_GRADUATION='graduation'
EDUCATION_CATEGORY_POST_GRADUATION='post_graduation'
EDUCATION_CATEGORY_OTHER='other'

EDUCATION_CATEGORY_CHOICES=((EDUCATION_CATEGORY_SSC, EDUCATION_CATEGORY_SSC),
                            (EDUCATION_CATEGORY_HSC, EDUCATION_CATEGORY_HSC),
                            (EDUCATION_CATEGORY_DIPLOMA,EDUCATION_CATEGORY_DIPLOMA),
                            (EDUCATION_CATEGORY_GRADUATION,EDUCATION_CATEGORY_GRADUATION),
                            (EDUCATION_CATEGORY_OTHER, EDUCATION_CATEGORY_OTHER))

FAIL='fail'
PASS='pass'
FIRST_CLASS='first_class'
SECOND_CLASS='second_class'
HIGHER_SECOND_CLASS='higher_second_class'
PURSUING='pursuing'


EDUCATION_GRADE_CHOICES=((FAIL, FAIL),
                        (PASS, PASS),
                        (FIRST_CLASS,FIRST_CLASS),
                        (SECOND_CLASS,SECOND_CLASS),
                        (HIGHER_SECOND_CLASS, HIGHER_SECOND_CLASS),
                        (PURSUING, PURSUING))
